---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-service-operator
spec:
  chart:
    spec:
      chart: azure-service-operator
      version: "v2.0.0-beta.3"
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: flux-system
  values:
    # Source: https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator/values.yaml
    createAzureOperatorSecret: true
    useWorkloadIdentityAuth: true
    azureSubscriptionID: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
    azureTenantID: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
    azureClientID: "a91a06f8-9fb3-4d13-9e40-a9c297fd3226"
  interval: 5m
