---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-services
  namespace: flux-system
spec:
  dependsOn:
    - name: system-infra
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-config
  path: ./gitops/platform/demo/services
  prune: true
  validation: server
