---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-identity-webhook
spec:
  chart:
    spec:
      chart: workload-identity-webhook
      version: "0.14.0"
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: flux-system
  values:
    # Source: https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/values.yaml
    azureTenantID: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
  interval: 5m
