apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cosmos-todo-app
  name: cosmos-todo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-todo-app
  template:
    metadata:
      labels:
        app: cosmos-todo-app
    spec:
      containers:
      - name: app
        image: mcr.microsoft.com/k8s/asodemos/cosmostodo:latest
        env:
          - name: CosmosDB__Account
            valueFrom:
              secretKeyRef:
                name: cosmos-connection-settings  # This is the secret created by ASO associated with the CosmosDB Account. See the DatabaseAccount resource for more details.
                key: documentEndpoint
                optional: false
          - name: CosmosDB__Key
            valueFrom:
              secretKeyRef:
                key: key
                name: cosmos-connection-settings  # This is the secret created by ASO associated with the CosmosDB Account. See the DatabaseAccount resource for more details.
                optional: false
          - name: CosmosDB__DatabaseName
            value: "db-cs-aso-gitops-demo"
          - name: CosmosDB__ContainerName
            value: "db-cs-aso-gitops-demo-container"
        ports:
        - containerPort: 80
          name: webserver
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-todo-service
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cosmos-todo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmos-todo-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 20.73.104.117.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cosmos-todo-service
            port:
              number: 80